name: BedwarsLabor

main: ch.queksy.classes.BedwarsLaborMain
version: 1.0.0
api-version: 1.8.8
description: BedwarsPlugin a little bit like that from Hypixel
authors: [Joel Schaller, Andrea Allesandra Amato, Martin Brunner]